# Generated by Django 4.0.2 on 2022-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.CharField(default='01/01/2000', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='nurse',
            name='date_of_birth',
            field=models.CharField(default='01/01/2000', max_length=20),
        ),
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default='01/01/2000', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
